/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-06-25

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*****************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"
#include "bsp.h"
#include "Usart1.h"
#include <string.h>
#include "App.h"
#include "CommonGPIO.h"
#include "ADC1.h"
#include "multi_button.h" 
#include "I2C1.h"
#include "ExternalInterruption.h"

static App_Event_T * App_EventFunc[] = {
	&EXTI4_Event,
	NULL, };
static App_Schedule_T App_ScheduleFunc[] = {
	{0, 500, LED_Flicker},
	{0, 50, ADC1_StartTask},
	{0, TICKS_INTERVAL, button_ticks},
	{0, 500, I2C_CheckBusy},
	{0, 10, Ctrl_LEDsFunc},
	
	{0, 0, NULL}, };//门限不可更改

//循环累加校验和
uint8_t Check_Sum(uint8_t *Data, uint8_t len){
	uint8_t Sum = 0;
	while(len--){
		Sum += *Data++;
	}
	return Sum;
}

int main(void)
{
	static App_Schedule_T *pApp_ScheduleFunc = App_ScheduleFunc;
	static App_Event_T **pApp_EventFunc = App_EventFunc;
	/* TODO - Add your application code here */
	Bsp_Init();

	/* Infinite loop */
	while (1)
	{		
		if(MS_TimerTrigger(&pApp_ScheduleFunc->MS_Counting, pApp_ScheduleFunc->MS_Timer)){//LED闪烁
			pApp_ScheduleFunc->APP_Function();
		}
		if((++pApp_ScheduleFunc)->APP_Function == NULL){
			pApp_ScheduleFunc = App_ScheduleFunc;
		}
		
		if((*pApp_EventFunc)->Event_flag){
			(*pApp_EventFunc)->APP_Function();
			(*pApp_EventFunc)->Event_flag = false;
		}
		if(*(++pApp_EventFunc) == NULL){
			pApp_EventFunc = App_EventFunc;
		}
	}
}
