/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-06-25

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"
#include "bsp.h"
#include "Usart1.h"
#include <string.h>
/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

//循环累加校验和
uint8_t Check_Sum(uint8_t *Data, uint8_t len){
	uint8_t Sum = 0;
	while(len--){
		Sum += *Data++;
	}
	return Sum;
}
/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	/* TODO - Add your application code here */
	Bsp_Init();
	
	if(PWR_GetFlagStatus(PWR_FLAG_WU) == SET){//待机唤醒复位
		PWR_ClearFlag(PWR_FLAG_WU);
	}
	else{//上电复位
		/* 使能WKUP引脚的唤醒功能 */
		PWR_WakeUpPinCmd(PWR_WakeUpPin_1, ENABLE);
		/* 进入待机模式 */
		PWR_EnterSTANDBYMode();
	}

	/* Infinite loop */
	while (1)
	{
		if(Set_Usart1Data()->RXFinshFlag){
			float x,y;
			USART1_DATA_T *_Data = Set_Usart1Data();
			if((_Data->Len == 9) && (_Data->Data[_Data->Len - 1] == Check_Sum(_Data->Data, _Data->Len - 1))){
//				x = *(float *)&_Data->Data[0];
//				y = *(float *)&_Data->Data[4];
				memcpy(&x, &_Data->Data[0], 4);
				memcpy(&y, &_Data->Data[4], 4);
				if(x < -180){
					x = -180;
				}else if(x > 180){
					x = 180;
				}
				if(y < -180){
					y = -180;
				}else if(y > 180){
					y = 180;
				}
				TIM_SetCompare1(TIM16, x * 5 / 9 + 150);
				TIM_SetCompare1(TIM17, y * 5 / 9 + 150);
			}
//			USART1_SendBuf(_Data->Data, _Data->Len);
			_Data->RXFinshFlag = 0;
			_Data->Len = 0;
			USART1_RXEnable();
		}
	}
}
